// <auto-generated />
using System;
using System.Text.Json;
using HalfLifeMetrics.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HalfLifeMetrics.Server.Data.Migrations
{
    [DbContext(typeof(HalfLifeStatsDbContext))]
    [Migration("20250513171431_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HalfLifeMetrics.Server.Data.Entities.SessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("CloseReason")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SteamProfileUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IpAddress")
                        .HasDatabaseName("IDX_IpV4");

                    b.HasIndex("Nickname")
                        .HasDatabaseName("IDX_Nickname");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("HalfLifeMetrics.Server.Data.Entities.SessionEntity", b =>
                {
                    b.OwnsOne("HalfLifeMetrics.Server.Data.Entities.GeoIpLocationEntity", "GeoIpLocation", b1 =>
                        {
                            b1.Property<Guid>("SessionEntityId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision");

                            b1.Property<JsonDocument>("Metadata")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("Metadata");

                            b1.HasKey("SessionEntityId");

                            b1.ToTable("Sessions");

                            b1.WithOwner()
                                .HasForeignKey("SessionEntityId");
                        });

                    b.Navigation("GeoIpLocation");
                });
#pragma warning restore 612, 618
        }
    }
}
