name: Build and Push Docker Image

on:
  push:
    branches: ["main"]
    tags: ["v*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker tags
        id: vars
        run: |
          IMAGE_NAME=chappy1989/halflifemetrics
          COMMIT_SHA=${GITHUB_SHA::7}

          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            TAG_NAME=${GITHUB_REF#refs/tags/}
            echo "tagged=${IMAGE_NAME}:${TAG_NAME}" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF}" == refs/heads/* ]]; then
            BRANCH_NAME=${GITHUB_REF#refs/heads/}
            SAFE_BRANCH_NAME=$(echo "$BRANCH_NAME" | tr '/' '-')
            echo "tagged=${IMAGE_NAME}:${SAFE_BRANCH_NAME}" >> $GITHUB_OUTPUT
          fi

          echo "latest=${IMAGE_NAME}:latest" >> $GITHUB_OUTPUT
          echo "commit=${IMAGE_NAME}:${COMMIT_SHA}" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./source/HalfLifeStats.Server/Dockerfile
          push: true
          tags: |
            ${{ steps.vars.outputs.tagged }}
            ${{ steps.vars.outputs.latest }}
            ${{ steps.vars.outputs.commit }}
